### ISSUE TITLE
单摄像头设备

### ISSUE THREAD

**Issue by fyc** [AnyLifeZLB/FaceSearchSDK_Android#4]
只有一个摄像头的设备会出现：
Camera LensFacing verification failed, existing cameras: [Camera@106939f[id=0]]
2013-01-18 21:51:55.681  1675-1731  CameraX                 com.ai.facesearch.demo               E  The device might underreport the amount of the cameras. Finish the initialize task since we are already reaching the maximum number of retries.
2013-01-18 21:51:55.706  1675-1675  AndroidRuntime          com.ai.facesearch.demo               D  Shutting down VM
2013-01-18 21:51:55.709  1675-1675  AndroidRuntime          com.ai.facesearch.demo               E  FATAL EXCEPTION: main
                                                                                                    Process: com.ai.facesearch.demo, PID: 1675
                                                                                                    java.lang.IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case
                                                                                                    	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:476)
                                                                                                    	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:363)
                                                                                                    	at com.ai.face.base.view.CameraXFragment.a(CameraXFragment.java:158)
                                                                                                    	at com.ai.face.base.view.CameraXFragment.$r8$lambda$Fo17bs64qzq80bHM5MJ_zt4yukI(CameraXFragment.java)
                                                                                                    	at com.ai.face.base.view.CameraXFragment$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:755)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6141)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by AnyLifeZLB** [comment]
你好，目前Demo 默认使用前置摄像头演示。如果只有一个摄像头的设备看看是否在设备上定义此摄像头为前前走，你可以更改默认摄像头尝试

        // 1. Camera 的初始化
        int cameraLens = sharedPref.getInt("cameraFlag", sharedPref.getInt("cameraFlag", 0));


还有问题随时反馈

**Comment by ly-alan** [comment]
单摄像头设备，CameraXFragment.newInstance()传入参数0或者1都还是会抛出这个错误
